server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA Flutter: semua route diarahkan ke index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # index.html jangan di-cache (agar update langsung kebaca)
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
